//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoex2.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public History_Sales()
        {
            this.Agent = new HashSet<Agent>();
        }
    
        public int ID { get; set; }
        public int id_Products { get; set; }
        public int id_Agent { get; set; }
        public Nullable<System.DateTime> Date_Realiz { get; set; }
        public Nullable<double> Count_Product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agent> Agent { get; set; }
        public virtual Agent Agent1 { get; set; }
        public virtual Products Products { get; set; }
    }
}
