//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoex2.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.History_Sales = new HashSet<History_Sales>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int ID_type { get; set; }
        public Nullable<int> article { get; set; }
        public Nullable<int> mans { get; set; }
        public Nullable<double> number_ceha { get; set; }
        public Nullable<decimal> min_price { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<double> razmer_ypakovki { get; set; }
        public Nullable<double> ves_bez { get; set; }
        public Nullable<double> ves_s { get; set; }
        public string servificate { get; set; }
        public string num_standart { get; set; }
        public Nullable<int> ID_history_product { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Sales> History_Sales { get; set; }
        public virtual Product_Type Product_Type { get; set; }
    }
}
